apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-home
  namespace: argocd
spec:
  description: The home application environments
  sourceRepos:
    - placeholder
  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'home-*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
