apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/component: bootstrap
    hempire.money/app-type: cluster-infra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cluster-services
  source:
    repoURL: placeholder
    targetRevision: placeholder
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
