apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas
  namespace: nas-config-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: truenas
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: truenas
