apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate
  namespace: renovate
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 12021
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:44.82.3
              env:
                - name: RENOVATE_PLATFORM
                  value: github
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: token
                - name: RENOVATE_AUTODISCOVER
                  value: "true"
                - name: RENOVATE_ONBOARDING
                  value: "false"
                - name: RENOVATE_REQUIRE_CONFIG
                  value: required
                - name: RENOVATE_GIT_AUTHOR
                  value: Renovate <renovate@users.noreply.github.com>
                - name: RENOVATE_REPOSITORY_CACHE
                  value: enabled
                - name: RENOVATE_BASE_DIR
                  value: /tmp/renovate
                - name: LOG_LEVEL
                  value: info
              volumeMounts:
                - name: cache
                  mountPath: /tmp/renovate
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                limits:
                  memory: 2Gi
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: renovate
