apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: renovate
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: renovate
