apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-services
  namespace: argocd
  labels:
    hempire.money/app-type: cluster-infra
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: cluster-services
  source:
    repoURL: placeholder
    targetRevision: placeholder
    path: services
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
