apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  labels:
    hempire.money/app-type: cluster-infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cluster-services
  source:
    repoURL: ghcr.io/nginx/charts
    chart: nginx-gateway-fabric
    targetRevision: 2.7.0
    helm:
      valuesObject:
        nginxGateway:
          gwAPIExperimentalFeatures:
            enable: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
