apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: pgadmin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: '{{ .password }}'
        pgpass: '{{ .pgpass }}'
        allowedLogins: '{{ .allowedLogins }}'
        config_local.py: |
          LOG_FILE = '/var/lib/pgadmin/pgadmin4.log'

          AUTHENTICATION_SOURCES = ['oauth2', 'internal']
          MASTER_PASSWORD_REQUIRED = True
          MASTER_PASSWORD_HOOK = '/hooks/master-password.sh %u'
          OAUTH2_AUTO_CREATE_USER = True

          OAUTH2_CONFIG = [
              {
                  'OAUTH2_NAME': 'github',
                  'OAUTH2_DISPLAY_NAME': 'GitHub',
                  'OAUTH2_CLIENT_ID': {{ .clientId | quote }},
                  'OAUTH2_CLIENT_SECRET': {{ .clientSecret | quote }},
                  'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
                  'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
                  'OAUTH2_API_BASE_URL': 'https://api.github.com/',
                  'OAUTH2_USERINFO_ENDPOINT': 'user',
                  'OAUTH2_SERVER_METADATA_URL': None,
                  'OAUTH2_SCOPE': 'read:user user:email',
                  'OAUTH2_USERNAME_CLAIM': 'login',
                  'OAUTH2_ICON': 'fa-github',
                  'OAUTH2_BUTTON_COLOR': '#3253a8',
                  'OAUTH2_ADDITIONAL_CLAIMS': {
                      'login': {{ .allowedLogins | splitList "," | toJson }},
                  },
              },
          ]
  data:
    - secretKey: clientId
      remoteRef:
        key: pgadmin
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: pgadmin
        property: clientSecret
    - secretKey: allowedLogins
      remoteRef:
        key: pgadmin
        property: allowedLogins
    - secretKey: password
      remoteRef:
        key: pgadmin
        property: password
    - secretKey: pgpass
      remoteRef:
        key: pgadmin
        property: pgpass
