apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:volsync-block-backed
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
  - apiGroups: [external-secrets.io]
    resources: [externalsecrets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [volsync.backube]
    resources: [replicationsources, replicationdestinations]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, watch]
