apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-secrets
  namespace: zitadel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: zitadel-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        db-host: zitadel-db-rw.zitadel.svc.cluster.local
        db-user: zitadel
        db-password: "{{ .dbPassword }}"
        masterkey: "{{ .masterkey }}"
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: dbPassword
      remoteRef:
        key: zitadel
        property: db-password
    - secretKey: masterkey
      remoteRef:
        key: zitadel
        property: masterkey
    - secretKey: adminPassword
      remoteRef:
        key: zitadel
        property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-db-app
  namespace: zitadel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: zitadel-db-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: zitadel
        password: "{{ .dbPassword }}"
  data:
    - secretKey: dbPassword
      remoteRef:
        key: zitadel
        property: db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3
  namespace: zitadel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: s3
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: s3
