apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  instances: 1

  storage:
    storageClass: database
    size: 20Gi

  bootstrap:
    recovery:
      source: backup

  externalClusters:
    - name: backup
      barmanObjectStore:
        destinationPath: s3://backups/zitadel
        endpointURL: placeholder
        serverName: zitadel-db
        s3Credentials:
          accessKeyId:
            name: s3
            key: access-key
          secretAccessKey:
            name: s3
            key: secret-key
        wal:
          maxParallel: 8

  managed:
    roles:
      - name: zitadel
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: zitadel-db-app


  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://backups/zitadel
      endpointURL: placeholder
      serverName: zitadel-db-r1
      s3Credentials:
        accessKeyId:
          name: s3
          key: access-key
        secretAccessKey:
          name: s3
          key: secret-key
      wal:
        compression: gzip

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: zitadel-db
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zitadel
  namespace: zitadel
spec:
  cluster:
    name: zitadel-db
  name: zitadel
  owner: zitadel
