apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  instances: 3

  storage:
    storageClass: database
    size: 20Gi

  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: zitadel-db-app

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://cnpg/zitadel
      endpointURL: placeholder
      s3Credentials:
        accessKeyId:
          name: s3
          key: access-key
        secretAccessKey:
          name: s3
          key: secret-key
      wal:
        compression: gzip

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: zitadel-db
