apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://backups/zitadel
    endpointURL: placeholder
    s3Credentials:
      accessKeyId:
        name: s3
        key: access-key
      secretAccessKey:
        name: s3
        key: secret-key
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-db
  namespace: zitadel
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 1

  storage:
    storageClass: database
    size: 20Gi

  bootstrap:
    recovery:
      source: backup

  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: zitadel-db
          serverName: zitadel-db-r2

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: zitadel-db
        serverName: zitadel-db-r2

  managed:
    roles:
      - name: zitadel
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: zitadel-db-owner


  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  schedule: "0 0 3 * * *"
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: zitadel-db
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zitadel
  namespace: zitadel
spec:
  cluster:
    name: zitadel-db
  name: zitadel
  owner: zitadel
