apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../config
  - nginx-gateway-namespace.yaml
  - clustersecretstore.yaml
  - democratic-csi-config.yaml
  - letsencrypt-issuer.yaml
  - pool.yaml
  - gateway.yaml
  - home-gateway.yaml
  - kafka
  - redis
  - zitadel
  - argocd
  - monitoring
  - pgadmin
  - renovate
  - volsync

patches:
  - target:
      kind: ConfigMap
      name: cluster-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: cluster-services-config

replacements:
  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.LETSENCRYPT_EMAIL
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt
        fieldPaths:
          - spec.acme.email
      - select:
          kind: Deployment
          name: pgadmin
        fieldPaths:
          - spec.template.spec.containers.[name=pgadmin].env.[name=PGADMIN_DEFAULT_EMAIL].value
          - spec.template.spec.initContainers.[name=seed].env.[name=PGADMIN_DEFAULT_EMAIL].value

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.METALLB_POOL
    targets:
      - select:
          kind: IPAddressPool
          name: cluster
        fieldPaths:
          - spec.addresses.0

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.S3_ENDPOINT
    targets:
      - select:
          kind: ObjectStore
          name: zitadel-db
        fieldPaths:
          - spec.configuration.endpointURL

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.S3_BACKUP_BUCKET
    targets:
      - select:
          kind: ObjectStore
          name: zitadel-db
        fieldPaths:
          - spec.configuration.destinationPath
        options:
          delimiter: '/'
          index: 2

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.GITHUB_ORG
    targets:
      - select:
          kind: ConfigMap
          name: argocd-cm
        fieldPaths:
          - data.dex\.config
        options:
          delimiter: 'name: '
          index: 2

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.DNS_ZONE
    targets:
      - select:
          kind: Certificate
        reject:
          - kind: Certificate
            name: home-wildcard-tls
        fieldPaths:
          - spec.dnsNames.0
        options:
          delimiter: '.'
          index: 1
      - select:
          kind: TLSRoute
        fieldPaths:
          - spec.hostnames.0
        options:
          delimiter: '.'
          index: 1
      - select:
          kind: ConfigMap
          name: argocd-cm
        fieldPaths:
          - data.url
        options:
          delimiter: '.'
          index: 1
      - select:
          kind: Deployment
          name: zitadel
        fieldPaths:
          - spec.template.spec.containers.[name=zitadel].env.[name=ZITADEL_EXTERNALDOMAIN].value
        options:
          delimiter: '.'
          index: 1

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.GATEWAY_IP
    targets:
      - select:
          kind: Gateway
          name: gateway
        fieldPaths:
          - spec.infrastructure.annotations.metallb\.universe\.tf/loadBalancerIPs

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.HOME_GATEWAY_IP
    targets:
      - select:
          kind: Gateway
          name: home
        fieldPaths:
          - spec.infrastructure.annotations.metallb\.universe\.tf/loadBalancerIPs

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.HOME_ZONE
    targets:
      - select:
          kind: Certificate
          name: home-wildcard-tls
        fieldPaths:
          - spec.dnsNames.0
        options:
          delimiter: '.'
          index: 1
      - select:
          kind: Gateway
          name: home
        fieldPaths:
          - spec.listeners.0.hostname
        options:
          delimiter: '.'
          index: 1

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.DNS_ZONE
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt
        fieldPaths:
          - spec.acme.solvers.0.selector.dnsZones.0

  - source:
      kind: ConfigMap
      name: cluster-services-config
      fieldPath: data.HEMPIRE_ZONE
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt
        fieldPaths:
          - spec.acme.solvers.1.selector.dnsZones.0
