apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster
  namespace: metallb-system
spec:
  addresses:
    - placeholder
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cluster
  namespace: metallb-system
spec:
  ipAddressPools:
    - cluster
