apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-auth
  namespace: registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: zot-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        htpasswd: |
          ci:{{ .ciPasswordHash }}
          puller:{{ .pullerPasswordHash }}
  data:
    - secretKey: ciPasswordHash
      remoteRef:
        key: zot
        property: ciPasswordHash
    - secretKey: pullerPasswordHash
      remoteRef:
        key: zot
        property: pullerPasswordHash
