apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: dex.github.clientId
      remoteRef:
        key: argocd-oidc
        property: clientId
    - secretKey: dex.github.clientSecret
      remoteRef:
        key: argocd-oidc
        property: clientSecret
