apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.3.1/deployments/multus-daemonset-thick.yml

images:
  - name: ghcr.io/k8snetworkplumbingwg/multus-cni
    newTag: v4.3.1-thick

patches:
  - target:
      kind: DaemonSet
      name: kube-multus-ds
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: system-node-critical
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
