apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: grafana-oidc
        property: clientId
    - secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: grafana-oidc
        property: clientSecret
