apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: grafana-admin
        property: password
