apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector: {}
  jobLabel: app
  podMetricsEndpoints:
    - port: metrics
